spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
    show-sql: true

#  redis:
#    host: localhost
#    port: 6379

  config:
    activate:
      on-profile: local
#    import:
#      application-secret.yml

oauth:
  apple:
    iss: ${APPLE_ISSUE}
    client-id: ${APPLE_BUNDLE_ID}
    key:
      path: /key/AuthKey_9LA3NLSR6X.p8

jwt:
  secret: ${JWT_SECRET}

app:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    callback:
      url: http://localhost:8080/auth/google/callback
    client:
      id: 719044852761-5aiakgngg693sa7822dk7b7je52ieo11.apps.googleusercontent.com
      secret: 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
    auth:
      scope: profile,email,openid
    token:
      url: https://oauth2.googleapis.com/token
    userinfo:
      url: https://www.googleapis.com/oauth2/v1/userinfo





