spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://troth-cam.crojjqnidysp.ap-northeast-2.rds.amazonaws.com:3306/trothcam_prod?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: trothly
    password: teamtrothly

  config:
    activate:
      on-profile: prod
#    import: application-secret.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    # Initial Data config
    defer-datasource-initialization: true