spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://troth-cam.crojjqnidysp.ap-northeast-2.rds.amazonaws.com:3306/trothcam_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: trothly
    password: teamtrothly

  config:
    activate:
      on-profile: prod
  #    import: application-secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    # Initial Data config
    defer-datasource-initialization: true

#  redis:
#    host: localhost
#    port: 6379

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: com.parkjju.trothcam
    key:
      path: /key/AuthKey_9LA3NLSR6X.p8

jwt:
  secret: a2FrYW9jbG91ZHNjaG9vbGxvY2Fsa2FrYW9jbG91ZGMK

app:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    callback:
      url: https://trothly.com/auth/google/callback
    client:
      id: 719044852761-5aiakgngg693sa7822dk7b7je52ieo11.apps.googleusercontent.com
      secret: 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
    auth:
      scope: profile,email,openid
    token:
      url: https://oauth2.googleapis.com/token
    userinfo:
      url: https://www.googleapis.com/oauth2/v1/userinfo