spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000
#  redis:
#    host: localhost
#    port: 6379

  config:
    activate:
      on-profile: local
#    import:
#      application-secret.yml

oauth:
  apple:
    iss: ${APPLE_ISSUE}
    client-id: ${APPLE_BUNDLE_ID}
